[package]
name = "cli"
version = "0.1.0"
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
authors = ["Christian Fuchte <christian.fuchte@grb-online.net>"]

[dependencies]
clap = { version = "4.5.41", features = ["cargo"] }
